apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx-app
  template: 
      metadata:
        name: nginx-pod
        labels:
          app: nginx-app
      spec:
        containers:
          - name: nginx
            image: nginx:latest
